#!/bin/sh

if [ $# -ne 1 ] ; then
  echo "Usage: $0 disk"
  exit 1
fi

# write stage 1 section of bootloader (without modifying the MBR)
dd if=bl1.bin of=$1 bs=1 count=442

# write stage 2 section of bootloader
dd if=bl1.bin of=$1 bs=512 skip=1 seek=1

# write u-boot
dd if=u-boot.bin of=$1 bs=512 seek=64
