#!/bin/bash

# By default 1) install the registration key, 2) install the wvdial.conf with the AoT APN,
# 3) disable sudo, and 4) set the AoT root password.
#
# Disable any of these actions except #1 with approprite options


PRINT_USAGE=0
DISABLE_WVDIAL=0
DISABLE_APN=0
ENABLE_SUDO=0
DISABLE_ROOT_PASS=0
CLEAN_UP=0
KEY_PATH='/root/id_rsa_waggle_aot_config'
MOUNT_POINT=''
while [[ $# -gt 0 ]]; do
  opt="$1"
  arg="$2"
  # echo "Key: $key"
  case $opt in
    --help)
      PRINT_USAGE=1
      ;;
    -w|--disable-wvdial)
      DISABLE_WVDIAL=1
      ;;
    -a|--disable-apn)
      DISABLE_APN=1
      ;;
    -s|--enable-sudo)
      ENABLE_SUDO=1
      ;;
    -r|--disable-root-pass)
      DISABLE_ROOT_PASS=1
      ;;
    -c|--clean-up)
      CLEAN_UP=1
      ;;
    -k)
      KEY_PATH="$arg"
      shift
      ;;
    --key-path=*)
      KEY_PATH="${opt#*=}"
      ;;
      *)
        MOUNT_POINT="$opt"
      ;;
  esac
  shift
done

declare -r USAGE_MESSAGE="Usage: bless-image [--help] [-w|--disable-wvdial] [-a|--disable-apn] [-s|--enable-sudo] [-r|--disable-root-pass] [-c|--clean-up] [-k <key-path>|--key-path=<key-path>] <mount-point>"
if [ ${PRINT_USAGE} -eq 1 ]; then
  echo
  echo ${USAGE_MESSAGE}
  echo
  exit 0
fi

if [ "x${MOUNT_POINT}" == "x" ]; then
  echo
  echo "Error: no mount point specified"
  echo ${USAGE_MESSAGE}
  echo
  exit 1
fi

if [ ! -e 'private_config' ]; then
  if [ ! -e ${KEY_PATH} ]; then
    echo "Error: no such key path ${KEY_PATH}"
    exit 2
  fi

  agent_pid=$(eval "$(ssh-agent -s)" | awk '{print $3}')
  ssh-add ${KEY_PATH}

  ssh -T git@github.com > /dev/null 2>&1
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
    echo "Error: unable to authenticate to GitHub"
    kill -9 ${agent_pid}
    exit 3
  fi
  git clone git@github.com:waggle-sensor/private_config.git
fi


# install registration key
cp private_config/id_rsa_waggle_aot_registration ${MOUNT_POINT}/root/id_rsa_waggle_aot_registration

# install wvdial.conf
if [ ${DISABLE_WVDIAL} -eq 0 ]; then
  cp private_config/wvdial.conf ${MOUNT_POINT}/etc/wvdial.conf
fi

# enable sudo
if [ ${ENABLE_SUDO} -eq 0 ]; then
  sed -i -e "s/^sudo:x:27:..*/sudo:x:27:waggle/" ${MOUNT_POINT}/etc/group
fi

# set AoT root password
if [ ${DISABLE_ROOT_PASS} -eq 0 ]; then
  aot_root_shadow_entry=$(cat private_config/root_shadow)
  sed -i -e "s/^root:..*/${aot_root_shadow_entry}/" ${MOUNT_POINT}/etc/shadow
fi

kill -9 ${agent_pid}


if [ ${CLEAN_UP} -eq 1 ]; then
  rm -rf private_config
fi
