#!/bin/bash

docker build -t waggle-node-controller:2.6.1-pre1 -f dockerfiles/waggle-node-controller --build-arg branch=develop --build-arg server_host=10.10.10.5 .
docker build -t waggle-edge-processor:2.6.1-pre1-f dockerfiles/waggle-edge-processor --build-arg branch=develop --build-arg server_host=10.10.10.5 .
