#!/usr/bin/python3

import getopt
import os
import os.path
import re
import shutil
import subprocess
import sys
import tempfile
import time

debug=0 # skip chroot environment if 1

waggle_image_directory = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, '%s/lib/python/' % waggle_image_directory)
from waggle.build import *

config_db_path = os.path.realpath('{}/config/build_config.json'.format(waggle_image_directory))
build_config = Configuration(str(config_db_path))

def print_usage():
    usage_message = "Usage: build-waggle-docker-image [OPTIONS]\n"\
                    "OPTIONS\n"\
                    "  --help                         "\
                    "show this usage message\n"\
                    "  -b |--build-dir=<build_dir>    "\
                    "work on the disk image in the <build_dir> directory\n"\
                    "  -n |--node-controller    "\
                    "build the Node Controller Waggle Docker image\n"\
                    "  -e |--edge-processor    "\
                    "build the Edge Processor Waggle Docker image\n"\
                    "  -v |--version=<version>    "\
                    "show this usage message\n"\
                    "  -r |--revision=<revision>    "\
                    "build revision <revision> of the specified version\n"\
                    "  -d |--deployment=<deployment>    "\
                    "configure the image according to deployment <deployment>\n"\
                    "  -t |--target=<target_dev>       "\
                    "target memory device (e.g. /dev/sdb) \n"\
                    "                                  to which the image should be written\n"\
                    "  -c|--compress                   "\
                    "compress the Waggle image\n"\
                    "  -u|--upload                     "\
                    "upload the compressed image to the Waggle\n"\
                    "                                  downloads page (implies -c)\n"\
                    ""
    print(usage_message)


def get_waggle_image_filename(build, node_element):
  node_element = node_element.replace(' ', '_').lower()

  device = None
  if node_element == 'node_controller':
      device = "odroid-c1"
  else:
      device = "odroid-xu3"

  base = None
  if node_element == 'Node Controller':
    base = build_config.get_base(eid=build['nc_base'])
  elif node_element == 'Edge Processor':
    base = build_config.get_base(eid=build['ep_base'])
  else:
    print("Error: unknown node element '{}'".format(node_element))
    sys.exit(6)

  version = build['published_version']
  revision = build['revision']

  return "waggle-{}-{}-{}-{}".format(node_element, device, version, revision)

def setup_mount_point(mount_point):
  # install parted
  if subprocess.call('hash partprobe > /dev/null 2>&1', shell=True):
      run_command('apt-get install -y parted')

  # install pipeviewer
  if subprocess.call('hash pv > /dev/null 2>&1', shell=True):
      run_command('apt-get install -y pv')


  # clean up first
  print("Unmounting lingering images.")
  unmount_mountpoint(mount_point)


  print("Detaching loop devices.")
  time.sleep(3)
  detach_loop_devices()

  create_loop_devices()


def get_base_image_filename(base):
    node_element = build_config.get_node_element(eid=base['node_element'])['name'].replace(
        ' ', '_').lower()
    if node_element == 'node_controller':
        device = "odroid-c1"
    else:
        device = "odroid-xu3"

    date = base['date'].replace('-', '')

    base_image_base="waggle-base-%s-%s-%s" % (node_element, device, date)
    return "{}.img".format(base_image_base)


def mount_new_image(build, node_element, mount_point, build_directory):
  base = None
  if node_element == 'Node Controller':
    base = build_config.get_base(eid=build['nc_base'])
  elif node_element == 'Edge Processor':
    base = build_config.get_base(eid=build['ep_base'])
  else:
    print("Error: unknown node element '{}'".format(node_element))
    sys.exit(6)
  base_image = get_base_image_filename(base)
  base_image_xz = base_image + '.xz'

  waggle_image = get_waggle_image_filename(build, node_element)
  waggle_image_xz = waggle_image + '.xz'

  waggle_downloads_url='http://www.mcs.anl.gov/research/projects/waggle/downloads/waggle_images/base/'

  if not os.path.isfile(base_image_xz):
    run_command('wget -P {} {}{}'.format(build_directory, waggle_downloads_url, base_image_xz))

  try:
      os.remove(waggle_image_xz)
  except:
      pass

  if not os.path.isfile(waggle_image_xz):
      print("Copying file %s to %s ..." % (base_image_xz, waggle_image_xz))
      shutil.copyfile(base_image_xz, waggle_image_xz)

  if not os.path.isfile(waggle_image):
      print("Uncompressing file %s ..." % waggle_image_xz)
      run_command('unxz ' + waggle_image_xz)

  attach_loop_devices(waggle_image, 0)

  time.sleep(3)
  print("first filesystem check on /dev/loop0p2")
  check_data_partition()

  print("execute: mkdir -p "+mount_point)
  try:
      os.mkdir(mount_point)
  except:
      pass

  mount_mountpoint(0, mount_point)


def stage_image_build_script(waggle_image_directory, mount_point):
  run_command('mkdir -p {0}/usr/lib/waggle'.format(mount_point))
  shutil.copyfile(waggle_image_directory+'/scripts/install_waggle.sh',
                  '{0}/usr/lib/waggle/install_waggle.sh'.format(mount_point))


def generate_repositories_string(build, repositories):
  version = build['published_version']
  revision = build['revision']
  repository_strings = []
  for repository in repositories:
    if revision == 0:
      repository_strings.append("{}:v{}".format(repository, version))
    else:
      repository_strings.append("{}:{}".format(repository, build[repository+'_commit']))
  return ','.join(repository_strings)


def build_image(build, node_element, mount_point):
  print('Building {} Waggle image...'.format(node_element))
  repositories_string = ''
  if node_element == 'Node Controller':
    base = build_config.get_base(eid=build['nc_base'])
    if base == None:
      print("Error: unable to find base with DB id '{}'".format(build['nc_base']))
      sys.exit(5)
    repositories = ['core', 'nodecontroller', 'plugin_manager']
    repositories_string = generate_repositories_string(build, repositories)
  elif node_element == 'Edge Processor':
    base = build_config.get_base(eid=build['nc_base'])
    if base == None:
      print("Error: unable to find base with DB id '{}'".format(build['ep_base']))
      sys.exit(5)
    repositories = ['core', 'edge_processor']
    repositories_string = generate_repositories_string(build, repositories)

  run_command('chroot {}/ /bin/bash /usr/lib/waggle/install_waggle.sh {} {}'.format(
    mount_point, server_host, repositories_string))

  os.remove('{0}/usr/lib/waggle/install_waggle.sh'.format(mount_point))

def generate_report(build_directory, mount_point, waggle_image):
  report_file = "report.txt"
  build_report = os.path.realpath("{}/root/{}".format(mount_point, report_file))
  image_report = "{}.{}".format(waggle_image, report_file)
  try:
    os.remove(image_report)
  except:
    pass

  print("copy: ", build_report, image_report)

  if os.path.exists(build_report):
    shutil.copyfile(build_report, image_report)
  else:
    print("file not found:", build_report)


def unmount_image(mount_point):
  unmount_mountpoint(mount_point)
  time.sleep(3)
  detach_loop_devices()
  time.sleep(3)


def compress_image(waggle_image):
  waggle_image_xz = waggle_image + '.xz'
  try:
    os.remove(waggle_image_xz)
  except:
    pass

  run_command('xz -1 %s' % waggle_image)


def upload_image(deployment, build_directory, waggle_image):
  if deployment['name'] != 'Public':
    print('Error: refusing to upload a non-public Waggle image to a public web site!')
    sys.exit(7)

  if not os.path.isfile( build_directory+ '/waggle-id_rsa'):
      return
  remote_path = '/mcs/www.mcs.anl.gov/research/projects/waggle/downloads/waggle_images/base/'
  scp_target = 'waggle@terra.mcs.anl.gov:' + remote_path
  run_command('md5sum $(basename {0}.xz) > {0}.xz.md5sum'.format(waggle_image) )


  cmd = 'scp -o "StrictHostKeyChecking no" -v -i {0}/waggle-id_rsa {1}.xz {1}.xz.md5sum {2}'.format(build_directory, waggle_image, scp_target)

  count = 0
  while 1:
    count +=1
    if (count >= 10):
      print("error: scp failed after 10 trys\n")
      sys.exit(1)

    cmd_return = 1
    print("execute: ", cmd)
    try:
      child = subprocess.Popen(['/bin/bash', '-c', cmd])
      child.wait()
      cmd_return = child.returncode

    except Exception as e:
      print("Error: %s" % (str(e)))
      cmd_return = 1

    if cmd_return == 0:
      break

    time.sleep(10)


  run_command('echo "{0}" > {1}/latest.txt'.format(waggle_image + ".xz", build_directory))
  run_command('scp -o "StrictHostKeyChecking no" -i {0}/waggle-id_rsa {0}/latest.txt {1}/'.format(build_directory, scp_target))


  if os.path.isfile(waggle_image +'.report.txt'):
    run_command('scp -o "StrictHostKeyChecking no" -v -i {0}/waggle-id_rsa {1}.report.txt {2}'.format(build_directory, waggle_image,scp_target))


  if os.path.isfile( waggle_image +'.build_log.txt'):
    run_command('scp -o "StrictHostKeyChecking no" -v -i {0}/waggle-id_rsa {1}.build_log.txt {2}'.format(build_directory, waggle_image,scp_target))

def burn_image(waggle_image, target_device):
  run_command('dd if={0} of={1} bs=100M status=progress'.format(waggle_image, target_device))


def deploy_to_disk(waggle_image, target_device):
  deploy_mount_point = tempfile.mkdtemp()
  run_command('mount {0}2 {1}'.format(target_device, deploy_mount_point))

  burn_image(waggle_image, target_device)

  deploy(deploy_mount_point)

  run_command('umount {0}'.format(deploy_mount_point))
  shutil.rmtree(deploy_mount_point)


# TODO: use the deployment details directly instead of converting them into parameters
#       for the bless-image script
def deploy(deployment, mount_point):
  disable_wvdial = ''
  wvdial_config = build_config.get_wireless_config(eid=deployment['wireless_config'])['name']
  if wvdial_config = 'Default':
    disable_wvdial = '--disable-wvdial '

  enable_sudo = ''
  if deployment['sudo']:
    enable_sudo = '--enable-sudo '

  disable_root_password = ''
  shadow_entry = build_config.get_shadow_entry(eid=deployment['shadow_entry'])['name']
  if shadow_entry == 'Default':
    disable_root_password = '--disable-root-password '

  rc = run_command('{0}/bless-image {1}{2}{3}{4} --clean-up'.format(
    waggle_image_directory, disable_wvdial, enable_sudo, disable_root_password, mount_point))
  if rc != 0:
    print("Error: bless-image failed with return code '{}'".format(rc))
    sys.exit(rc)

def main(argv):
  try:
    opts, args = getopt.getopt(
      argv, "b:nev:r:d:t:cu",
      ["help", "build-dir=", "node-controller", "edge-processor", "version=", "revision=", "deployment=",
       "target=", "compress", "upload"])
  except getopt.GetoptError as ge:
    print("\nError:", str(ge))
    print_usage()
    sys.exit(1)

    build_directory = './'
    node_controller = False
    edge_processor = False
    version = None
    revision = None
    deployment_name = 'Public'
    target_device=None
    compress = False
    upload = False
    for opt, arg in opts:
      if opt == '--help':
        print("\n" + usage_message + "\n")
        sys.exit(0)
      elif opt in ('-b', '--build-dir'):
        build_dir = arg
      elif opt in ('-n', '--node-controller'):
        node_controller = True
      elif opt in ('-e', '--edge-processor'):
        edge_processor = True
      elif opt in ('-v', '--version'):
        version = arg
      elif opt in ('-r', '--revision'):
        revision = int(arg)
      elif opt in ('-d', '--deployment'):
        deployment_name = arg
      elif opt in ('-t', '--target'):
        target_device = arg
    elif opt in ('-c', '--compress'):
      compress = True
      elif opt in ('-u', '--upload'):
        upload = True
      else:
        print("\n" + usage_message + "\n")
        sys.exit(2)

  architecture = 'armv7l'
  architecture_id = build_config.get_cpu_architecture(architecture)


  if version == None:
    version, tmp_revision = build_config.get_latest_build(architecture)
    if revision == None:
      revision = tmp_revision
  else:
    if revision == None:
      revision = int(0)

  deployment = build_config.get_deployment(deployment_name)
  if deployment == None:
    print("Error: unable to find deployment with name '{}'".format(deployment))
    sys.exit(3)

  server_host = build_config.get_beehive_host(eid=deployment['beehive_host'])['address']

  os.chdir(waggle_image_directory)
  branches = subprocess.check_output(['git', 'branch']).decode().split('\n')
  branch = [b for b in branches if '*' in b][0][2:]

  build = build_config.get_build(version, revision, architecture_id)

  # convert hostname to IP
  if re.search('[a-zA-Z]', server_host):
    hostname = server_host
    server_host = socket.gethostbyname(hostname)
    print("Resolved server host '{}' to IP '{}'.".format(hostname, server_host))

  create_b_image = 0 # will be 1 for XU3/4

  change_partition_uuid_script = waggle_image_directory + 'scripts/change-partition-uuid'   #'/usr/lib/waggle/waggle_image/change_partition_uuid.sh'

  mount_point = "/mnt/newimage"

  waggle_image = get_waggle_image_filename(build, node_element)

  setup_mount_point(mount_point)

  os.chdir(build_directory)

  mount_new_image(build, node_element, mount_point, build_directory)

  stage_image_build_script(waggle_image_directory, mount_point)

  build_image(build, node_element, mount_point)

  generate_report(build_directory, mount_point, waggle_image)

  if target_device != None:
    unmount_image(mount_point)
    deploy_to_disk(waggle_image, target_device)
  else:
    deploy(mount_point)
    unmount_image(mount_point)

  attach_loop_devices(waggle_image, 0)

  print("check boot partition")
  check_boot_partition()

  print("filesystem check on /dev/loop0p2 after chroot")
  check_data_partition()

  detach_loop_devices()

  if compress:
    compress_image(waggle_image)

  if upload:
    upload_image(deployment, build_directory, waggle_image)

if __name__ == '__main__':
  main(sys.argv[1:])
