#!/bin/bash

set -x

mount_disk() {
  local device=$1
  local mountpoint=$2
  mount ${device} ${mountpoint}
  mount -o bind /dev  ${mountpoint}/dev
  mount -o bind /proc ${mountpoint}/proc
  mount -o bind /run ${mountpoint}/run
  mount -o bind /sys  ${mountpoint}/sys
  sleep 3
}

mount_disk $1 $2
