#!/usr/bin/env python3

import getopt
import os
import os.path
import shutil
import subprocess
import sys
import tempfile
import time

waggle_image_directory = os.path.dirname(os.path.abspath(__file__))
#print("### Run directory for build_image.py: %s" % waggle_image_directory)
sys.path.insert(0, '%s/lib/python/' % waggle_image_directory)
from waggle.build import *

def main(args):
  image_filename = args[0]
  mount_point = args[1]

  create_loop_devices()

  attach_loop_devices(image_filename, 0)

  time.sleep(3)

  print("execute: mkdir -p "+mount_point)
  try:
      os.mkdir(mount_point)
  except:
      pass

  mount_mountpoint(0, mount_point)

if __name__ == '__main__':
  main(sys.argv[1:])
