#!/usr/bin/env python3

import getopt
import os
import os.path
import shutil
import subprocess
import sys
import tempfile
import time

waggle_image_directory = os.path.dirname(os.path.abspath(__file__))
#print("### Run directory for build_image.py: %s" % waggle_image_directory)
sys.path.insert(0, '%s/lib/python/' % waggle_image_directory)
from waggle.build import *

def main(args):
  mount_point = os.path.realpath(args[0])

  unmount_mountpoint(mount_point)

  time.sleep(3)

  print("Detaching loop devices.")
  detach_loop_devices()

if __name__ == '__main__':
  main(sys.argv[1:])
