#!/bin/bash

if [ ! -e /root/shadow_waggle ]; then
  echo "The shadow file not presented under /root/shadow_waggle"
  exit 2
fi

echo "Unlocking the Waggle system"
ln -sf /root/shadow_waggle /etc/shadow
if [ $? -eq 0 ];then
  echo "Unlocking is done"
else
  echo "Unlocking failed"
fi
