#!/bin/bash

if [ ! -e /root/shadow_aot ]; then
  echo "The shadow file not presented under /root/shadow_aot"
  exit 2
fi

echo "Locking the Waggle system"
ln -s /root/shadow_aot /etc/shadow

echo "Locking is done"