#!/bin/bash

source="$1"
output="$2"

if [ -z "$source" ] || [ -z "$output" ]; then
    echo "usage: source.img output_dir"
    exit 1
fi

device=$(losetup --show -fP "$source")

mkdir -p mnt/boot mnt/root "$output/boot" "$output/root" "$output/rw"

mount "$device"p1 mnt/boot
cp -a mnt/boot/. "$output/boot"
umount mnt/boot

mount "$device"p2 mnt/root
cp -a mnt/root/. "$output/root"
umount mnt/root

losetup -d "$device"
