#!/bin/bash

(
cd "$1"

if [ -d "root/var" ]; then
    echo "relinking image /var"
    rm -rf root/wagglerw/var rw/var
    mkdir -p root/wagglerw/var rw/var
    cp -a root/var/. root/wagglerw/var/.
    rm -rf root/var
    ln -s /wagglerw/var root/var
else
    echo "image /var ok"
fi

if [ -d "root/srv" ]; then
    echo "relinking image /srv"
    rm -rf root/wagglerw/srv rw/srv
    mkdir -p root/wagglerw/srv rw/srv
    cp -a root/srv/. root/wagglerw/srv/.
    cp -a root/srv/. rw/srv/.
    rm -rf root/srv
    ln -s /wagglerw/srv root/srv
else
    echo "image /srv ok"
fi

echo "copy root/wagglerw to rw partition"
cp -a root/wagglerw/. rw

echo "removing do_recovery"
rm -f root/root/do_recovery root/wagglerw/do_recovery rw/do_recovery
)
