#!/bin/bash

# TODO add back in aafirstboot to regen host ssh keys. or generate as image creation process?

log() {
    echo -e "\033[32m$(date +'%Y/%m/%d %H:%M:%S') - $*\033[0m"
}

fatal() {
    >&2 echo -e "\033[33m$(date +'%Y/%m/%d %H:%M:%S') - $*\033[0m"
    exit 1
}

usage() {
    cat << EOF
usage: $0 basedir device

basedir must be a directory of the form:

basedir/
    boot/               <- boot partition contents
    root/               <- root partition contents
    rw/                 <- rw partition contents
EOF
    exit 1
}

make_partitions() {
  if [ -z "$1" ]; then
    fatal "error: make_partitions requires a target device"
  fi

  dd if=/dev/zero of="$1" bs=1M count=100
  sync

  sleep 3

  parted --script "$1" mklabel msdos

  parted --script "$1" mkpart primary fat16 3072s 266239s
  parted --script "$1" set 1 lba off

  parted --script "$1" mkpart primary ext4 266240s 15624191s
  parted --script "$1" mkpart primary ext4 15624192s 100%

  sleep 3

  mkdosfs -F 16 "$1"1
  mkfs.ext2 -F "$1"2
  mkfs.ext2 -F "$1"3
}

generate_boot_ini() {
    if [ -z "$1" ]; then
      fatal "error: missing target device"
    fi

    root_uuid=$(blkid -s UUID -o value "$1"2)

    cat << EOF
ODROIDXU-UBOOT-CONFIG

# U-Boot Parameters
setenv initrd_high "0xffffffff"
setenv fdt_high "0xffffffff"

# Mac address configuration
setenv macaddr "00:1e:06:61:7a:39"

# --- Screen Configuration for HDMI --- #
# ---------------------------------------
# Uncomment only ONE line! Leave all commented for automatic selection.
# Uncomment only the setenv line!
# ---------------------------------------
# ODROID-VU forced resolution
# setenv videoconfig "video=HDMI-A-1:1280x800@60"
# -----------------------------------------------
# ODROID-VU forced EDID
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1280x800.bin"
# -----------------------------------------------
# 1920x1200 60hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x1200_60hz.bin"
# -----------------------------------------------
# 1920x1200 30hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x1200_30hz.bin"
# -----------------------------------------------
# 1920x1080 (1080P) with monitor provided EDID information. (1080p-edid)
# setenv videoconfig "video=HDMI-A-1:1920x1080@60"
# -----------------------------------------------
# 1920x1080 (1080P) without monitor data using generic information (1080p-noedid)
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x1080.bin"
# -----------------------------------------------
# 1920x1080 50hz (1080P) with monitor provided EDID information. (1080p 50hz-edid)
# setenv videoconfig "video=HDMI-A-1:1920x1080@50"
# -----------------------------------------------
# 1920x1080 50hz (1080P) without monitor data using generic information (1080p 50hz-noedid)
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x1080_50hz.bin"
# -----------------------------------------------
# 1920x1080 24Hz (1080P) without monitor data using generic information (1080p 24hz-noedid)
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x1080_24hz.bin"
# -----------------------------------------------
# 1920x1080 23.976Hz (1080P) without monitor data using generic information (1080p 23.976hz-noedid)
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x1080_23_976hz.bin"
# -----------------------------------------------
# 1920x800 60hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1920x800.bin"
# -----------------------------------------------
# 1792x1344 60hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1792x1344.bin"
# -----------------------------------------------
# 1680x1050 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1680x1050.bin"
# -----------------------------------------------
# 1600x1200 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1600x1200.bin"
# -----------------------------------------------
# 1600x900 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1600x900.bin"
# -----------------------------------------------
# 1400x1050 60hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1400x1050.bin"
# -----------------------------------------------
# 1440x900 with monitor provided EDID information.
# setenv videoconfig "video=HDMI-A-1:1440x900@60"
# -----------------------------------------------
# 1440x900 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1440x900.bin"
# -----------------------------------------------
# 1366x768 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1366x768.bin"
# -----------------------------------------------
# 1360x768 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1360x768.bin"
# -----------------------------------------------
# 1280x1024 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1280x1024.bin"
# -----------------------------------------------
# 1280x768 60hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1280x768.bin"
# -----------------------------------------------
# 1280x720 (720P) with monitor provided EDID information. (720p-edid)
# setenv videoconfig "video=HDMI-A-1:1280x720@60"
# -----------------------------------------------
# 1280x720 (720P) without monitor data using generic information (720p-noedid)
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1280x720.bin"
# -----------------------------------------------
# 1152x864 75hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1152x864_75hz.bin"
# -----------------------------------------------
# 1024x768 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1024x768.bin"
# -----------------------------------------------
# 1024x600 without monitor data using generic information (ODROID VU7+)
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/1024x600.bin"
# -----------------------------------------------
# 800x600 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/800x600.bin"
# -----------------------------------------------
# 848x480 60hz without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/848x480.bin"
# -----------------------------------------------
# 800x480 without monitor data using generic information (ODROID 7")
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/800x480.bin"
# -----------------------------------------------
# 720x576 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/720x576.bin"
# -----------------------------------------------
# 720x480 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/720x480.bin"
# -----------------------------------------------
# 640x480 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/640x480.bin"
# -----------------------------------------------
# 480x800 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/480x800.bin"
# -----------------------------------------------
# 480x320 without monitor data using generic information
# setenv videoconfig "drm_kms_helper.edid_firmware=edid/480x320.bin"

# --- HDMI / DVI Mode Selection ---
# ------------------------------------------
# - HDMI Mode
setenv vout "hdmi"
# - DVI Mode (disables sound over HDMI as per DVI compat)
# setenv vout "dvi"

# --- HDMI CEC Configuration ---
# ------------------------------------------
setenv cecenable "false" # false or true
# set to true to enable HDMI CEC

# Enable/Disable ODROID-VU7 Touchsreen
setenv disable_vu7 "false" # false

# DRAM Frequency
# Sets the LPDDR3 memory frequency
# Supported values: 933 825 728 633 (MHZ)
setenv ddr_freq 825

# External watchdog board enable
setenv external_watchdog "false"
# debounce time set to 3 ~ 10 sec, default 3 sec
setenv external_watchdog_debounce "3"


#------------------------------------------------------------------------------
#
# HDMI Hot Plug detection
#
#------------------------------------------------------------------------------
#
# Forces the HDMI subsystem to ignore the check if the cable is connected or
# not.
# false : disable the detection and force it as connected.
# true : let cable, board and monitor decide the connection status.
#
# default: true
#
#------------------------------------------------------------------------------
setenv HPD "true"

#------------------------------------------------------------------------------------------------------
# Basic Ubuntu Setup. Don't touch unless you know what you are doing.
# --------------------------------
setenv bootrootfs "console=tty1 console=ttySAC2,115200n8 root=UUID=${root_uuid} rootwait ro fsck.repair=yes net.ifnames=0"


# Load kernel, initrd and dtb in that sequence
fatload mmc 0:1 0x40008000 zImage
fatload mmc 0:1 0x42000000 uInitrd

setenv fdtloaded "false"
if test "x\${board_name}" = "x"; then setenv board_name "xu4"; fi
if test "\${board_name}" = "xu4"; then fatload mmc 0:1 0x44000000 exynos5422-odroidxu4.dtb; setenv fdtloaded "true"; fi
if test "\${board_name}" = "xu3"; then fatload mmc 0:1 0x44000000 exynos5422-odroidxu3.dtb; setenv fdtloaded "true"; fi
if test "\${board_name}" = "xu3l"; then fatload mmc 0:1 0x44000000 exynos5422-odroidxu3-lite.dtb; setenv fdtloaded "true"; fi
if test "\${fdtloaded}" = "false"; then fatload mmc 0:1 0x44000000 exynos5422-odroidxu4.dtb; setenv fdtloaded "true"; fi

fdt addr 0x44000000

setenv hdmi_phy_control "HPD=\${HPD} vout=\${vout}"
if test "\${cecenable}" = "false"; then fdt rm /cec@101B0000; fi
if test "\${disable_vu7}" = "false"; then setenv hid_quirks "usbhid.quirks=0x0eef:0x0005:0x0004"; fi
if test "\${external_watchdog}" = "true"; then setenv external_watchdog "external_watchdog=\${external_watchdog} external_watchdog_debounce=\${external_watchdog_debounce}"; fi

# final boot args
setenv bootargs "\${bootrootfs} \${videoconfig} \${hdmi_phy_control} \${hid_quirks} smsc95xx.macaddr=\${macaddr} \${external_watchdog}"

# set DDR frequency
dmc \${ddr_freq}

# Boot the board
bootz 0x40008000 0x42000000 0x44000000
EOF
}

generate_fstab() {
    if [ -z "$1" ]; then
      fatal "error: missing target device"
    fi

    case "$2" in
        ro) root_mode="ro" ;;
        rw) root_mode="rw" ;;
        *) fatal "error: invalid root fs mode. must be ro or rw"
    esac

    boot_uuid=$(blkid -s UUID -o value "$1"1)
    boot_type=$(blkid -s TYPE -o value "$1"1)

    root_uuid=$(blkid -s UUID -o value "$1"2)
    root_type=$(blkid -s TYPE -o value "$1"2)

    rw_uuid=$(blkid -s UUID -o value "$1"3)
    rw_type=$(blkid -s TYPE -o value "$1"3)

    cat << EOF
UUID=${root_uuid}  /       ${root_type}    ${root_mode},nosuid,nodev,nofail,noatime,nodiratime            0 1
UUID=${rw_uuid}      /wagglerw       ${rw_type}    errors=remount-ro,noatime,nodiratime            0 1
UUID=${boot_uuid} /media/boot ${boot_type}  defaults,rw,owner,flush,umask=000 0 0
tmpfs   /tmp  tmpfs nodev,nosuid,mode=1777      0 0
/wagglerw/var /var none bind
/wagglerw/srv /srv none bind
/run /var/run none bind
EOF
}

basedir=$1
device=$2
prefix=$3

if [ -z "$device" ]; then
    usage
fi

if [ -z "$prefix" ]; then
    prefix=$1
fi

log "partitioning disk"
make_partitions "$device"

cleanup() {
    log "unmounting partitions"
    umount partitions/*
}

trap cleanup EXIT

mkdir -p partitions/boot partitions/root partitions/rw

log "mounting partitions"
mount "$device"1 partitions/boot
mount "$device"2 partitions/root
mount "$device"3 partitions/rw

log "populating boot partition"
cp -r "$basedir"/boot/. partitions/boot

log "populating root partition"
cp -r "$basedir"/root/. partitions/root

log "populating rw partition"
cp -r "$basedir"/rw/. partitions/rw

log "generating boot.ini"
generate_boot_ini $device > partitions/boot/boot.ini

log "generating fstab"
generate_fstab $device rw > partitions/root/etc/fstab
generate_fstab $device rw > partitions/root/etc/fstab_rw
generate_fstab $device ro > partitions/root/etc/fstab_ro

log "writing bootloader"
(cd odroid_xu4_uboot; ./sd_fusing.sh $device)

sync
