#!/usr/bin/python3

import os
import os.path
import tkinter

import waggle.build as build

def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))


  app = build.ConfigurationEditor()
  app.run()
  # root.destroy() # optional; see description below

if __name__ == '__main__':
  main()
