#!/usr/bin/env python3

import os
import os.path
import tinydb

import waggle.build as build

def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))

  build_config = build.Configuration()

  for entry in build_config.get_registration_keys():
    print('{} {}: {}'.format(entry.eid, entry['name'], entry['file']))

if __name__ == '__main__':
  main()
