#!/usr/bin/env python3

import copy
import getopt
import os
import os.path
import re
import subprocess
import sys
import time

config_directory = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.realpath('{}/../lib/python/'.format(config_directory)))
import waggle.build as build

def main(argv):
  usage_message = \
    "Usage: get-base-dependencies --help\n" \
    "  print help screen\n" \
    "       get-base-dependencies <uuid>" \
    "  UUID of the base for which dependencies will be returned\n" \
    ""
  try:
    opts, args = getopt.getopt(argv, "", ["help"])
  except getopt.GetoptError as ge:
    print("\nError:", str(ge))
    print(usage_message + "\n")
    sys.exit(1)

  for opt, arg in opts:
    if opt == '--help':
      print("\n" + usage_message + "\n")
      sys.exit(0)
    else:
      print("\n" + usage_message + "\n")
      sys.exit(2)

  uuid = argv[0]

  script_dir = os.path.dirname(os.path.abspath(__file__))

  build_config = build.Configuration(os.path.join(script_dir, 'build_config.json'))

  print(build_config.get_base_dependencies(uuid))

if __name__ == '__main__':
  main(sys.argv[1:])
