#!/usr/bin/env python3

import os
import os.path
import tinydb

import waggle.build as build

def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))

  build_config = build.Configuration()

  for entry in build_config.get_deployments():
    print('{} {}:'.format(entry.eid, entry['name']))
    shadow_entry = build_config.get_shadow_entry(eid=entry['shadow_entry'])
    print('    Shadow Entry:     {}'.format(shadow_entry['name']))
    print('    Sudo Enabled:     {}'.format(entry['sudo']))
    wireless_config = build_config.get_wireless_config(eid=entry['wireless_config'])
    print('    Wireless Config:  {}'.format(wireless_config['name']))
    reg_key = build_config.get_registration_key(eid=entry['reg_key'])
    print('    Registration Key: {}'.format(reg_key['name']))
    beehive_host = build_config.get_beehive_host(eid=entry['beehive_host'])
    print('    Beehive Host:     {}'.format(beehive_host['name']))

if __name__ == '__main__':
  main()
