#!/usr/bin/env python3

import os
import os.path
import tinydb

import waggle.build as build

import inspect

def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))

  build_config = build.Configuration()

  for entry in build_config.get_builds():
    print(entry['deployment'])
    deployment = build_config.get_deployment(eid=entry['deployment'])
    print('{} {} ({}) {} {}:'.format(
      entry.eid, entry['published_version'], entry['revision'], deployment['name'], entry['date']))
    print('  Bases:')
    base_ids = [entry['nc_base'], entry['ep_base']]
    for base_id in base_ids:
      base = build_config.get_base(eid=base_id)
      print('    {} {} ({}) {} - {}:'.format(
        base.eid, build_config.get_node_element(eid=base['node_element'])['name'],
        build_config.get_cpu_architecture(eid=base['cpu_architecture'])['name'], base['date'],
        base['uuid']))
    print('  Commit IDs:')
    repos = ['waggle_image  ', 'core          ', 'nodecontroller', 'edge_processor', 'plugin_manager']
    keys = ['waggle_image_commit', 'core_commit', 'nc_commit', 'ep_commit', 'pm_commit']
    for repo,key in zip(repos, keys):
      print('    {} {}'.format(repo, entry[key]))


if __name__ == '__main__':
  main()
