#!/usr/bin/env python3

import os
import os.path
import tinydb

import waggle.build as build

def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))

  build_config = build.Configuration()

  for entry in build_config.get_bases():
    print('{} {} ({}) {} - {}:'.format(
      entry.eid, build_config.get_node_element(eid=entry['node_element'])['name'],
      build_config.get_cpu_architecture(eid=entry['cpu_architecture'])['name'], entry['date'],
      entry['uuid']))
    for dependency_id in entry['dependencies']:
      dependency = build_config.get_dependency(eid=dependency_id)
      print('  {} {} ({})'.format(
       dependency_id, dependency['name'],
         build_config.get_dependency_type(eid=dependency['type'])['name']))

if __name__ == '__main__':
  main()
