#!/usr/bin/env python3

import os
import os.path
import sys
import tinydb

config_directory = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.realpath('{}/../lib/python/'.format(config_directory)))
import waggle.build as build

def print_entries(entries):
  for entry in entries:
    name = entry['name']
    print('{} {}'.format(entry.eid, name))

def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))

  build_config = build.Configuration(os.path.join(script_dir, 'build_config.json'))

  print_entries(build_config.get_dependency_types())

if __name__ == '__main__':
  main()
