#!/usr/bin/python3

import os
import os.path
import tkinter

import waggle.build as build

def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))


  root = tkinter.Tk()
  root.wm_title("Waggle Remote Build Console")

  app = build.RemoteBuildConsole(root)

  root.mainloop()
  # root.destroy() # optional; see description below


  '''
  capture_config_file = '/etc/waggle/image_capture.conf'
  capture_config = None
  if os.path.isfile(capture_config_file):
    with open(capture_config_file) as config:
      capture_config = json.loads(config.read())
  else:
    capture_config = {'top':{'resolution':'1024x768', 'skip_frames':5, 'factor':90,
                             'interval':1800},
                      'bottom':{'resolution':'1920x1080', 'skip_frames':5, 'factor':90,
                                'interval':1800}}
    with open(capture_config_file, 'w') as config:
      config.write(json.dumps(capture_config))
  '''

if __name__ == '__main__':
  main()
