#!/bin/bash

if [ ! -e /root/shadow_aot ]; then
  echo "The shadow file not presented under /root/shadow_aot"
  exit 2
fi

echo "Locking the Waggle system"
ln -sf /root/shadow_aot /etc/shadow
if [ $? -eq 0 ];then
  echo "Locking is done"
else
  echo "Locking failed"
fi
